version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: backend_container
    ports:
      - "8000:8000"
    environment:
      - MODEL_PATH=/app/models/best_model.pkl
      - PIPELINE_PATH=/app/models/complete_pipeline.pkl

  frontend:
    build:
      context: ./frontend
    container_name: frontend_container
    ports:
      - "7860:7860"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:8000
